#!/bin/bash

cd /var/mobile/sinfool
rm Packages.bz2
ls debs | while read d
do
p=debs/"$d"
dpkg-deb -f $p >> Packages
echo "Filename: $p" >> Packages
echo "MD5sum: $(md5sum $p | cut -d " " -f1)" >> Packages
echo "Size: $(stat -c %s $p)" >> Packages
echo >> Packages
done
bzip2 -z Packages
echo "Currently $(ls debs | wc -l) packages on this repo" > readMe.md
echo >> readMe.md
echo "$(ls debs | grep -vc "debug") have been approved by our team as ready for use" >> readMe.md
git add --all
test "$1" = "" && {
git commit -m "Update"
} || {
git commit -m "$1"
}
sudo git push